### ISSUE TITLE
 I cannot decrypt a nca if it is a patch

### ISSUE THREAD

**Issue by D3fau4** [Thealexbarney/LibHac#196]
when i try do nca..OpenDecryptedNca(); i get this error:
```
LibHac.LibHacException: Abort:  must not be nullptr.
   at LibHac.Diag.Abort.DoAbort(String message)
   at LibHac.Diag.Assert.ExecuteAssertionFailureOperation(AssertionFailureOperation operation, AssertionInfo& assertionInfo)
   at LibHac.Diag.Assert.InvokeAssertionFailureHandler(AssertionInfo& assertionInfo)
   at LibHac.Diag.Assert.OnAssertionFailure(AssertionType assertionType, String condition, String functionName, String fileName, Int32 lineNumber, String message)
   at LibHac.Diag.Impl.AssertImpl.InvokeAssertionNotNull(AssertionType assertionType, String valueText, String functionName, String fileName, Int32 lineNumber)
   at LibHac.Diag.Assert.NotNullImpl[T](AssertionType assertionType, T value, String valueText, String functionName, String fileName, Int32 lineNumber)
   at LibHac.Diag.Assert.SdkRequiresNotNull[T](T value, String valueText, String functionName, String fileName, Int32 lineNumber)
   at LibHac.FsSystem.BucketTree.NodeBuffer.Allocate(Int32 nodeSize)
   at LibHac.FsSystem.BucketTree.Initialize(SubStorage nodeStorage, SubStorage entryStorage, Int32 nodeSize, Int32 entrySize, Int32 entryCount)
   at LibHac.FsSystem.Aes128CtrExStorage..ctor(IStorage baseStorage, SubStorage nodeStorage, SubStorage entryStorage, Int32 entryCount, Byte[] key, Byte[] counter, Boolean leaveOpen)
   at LibHac.FsSystem.NcaUtils.Nca.OpenAesCtrExStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorageWithPatch(Nca patchNca, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorageWithPatch(Nca patchNca, Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.FsSystem.NcaUtils.Nca.OpenFileSystemWithPatch(Nca patchNca, Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Mara.Switch.NCA.OpenFileSystem(Int32 index, Nca nca) in C:\Users\raul2\source\repos\Mara.switch\Mara.switch\NCA.cs:line 93
```

code:
```cs
            if (updatemountname != null)
            {
                foreach (DirectoryEntryEx entry in fs.EnumerateEntries(updatemountname.ToString(), "*.nca", SearchOptions.Default))
                {
                    Console.WriteLine(entry.FullPath);
                    fs.OpenFile(out FileHandle nca, entry.FullPath.ToU8Span(), OpenMode.Read);
                    //var meme = new Nca(hos.keys, new FileHandleStorage(fs, nca));
                    UpdateNcas.Add(new Nca(hos.keys, new FileHandleStorage(fs, nca)));
                }
            }
```

**Comment by Thealexbarney** [comment]
The issue is an incorrect assert here. It should be `Assert.SdkRequiresNull` instead of `Assert.SdkRequiresNotNull`
 https://github.com/Thealexbarney/LibHac/blob/1acdd86e27de16703fdb1c77f50ed8fd71bd3ad7/src/LibHac/FsSystem/BucketTree.cs#L277-L284
