### ISSUE TITLE
Invalid Partition FS type

### ISSUE THREAD

**Issue by kaktus40** [Thealexbarney/LibHac#226]
Hello,
I try to extract the module Id or build Id from an nsp file. My code works well for a bunch of files but I have an issue with two nsp which title Id are 01005FE01291A000 and 100947013122000.
For these files, I have this message:
`LibHac.HorizonResultException: ResultFsPartitionSignatureVerificationFailed (2002-4644): Invalid Partition FS type "?f??"
   at LibHac.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.FsSystem.PartitionFileSystemHeader..ctor(BinaryReader reader)
   at LibHac.FsSystem.PartitionFileSystem..ctor(IStorage storage)
   at LibHac.FsSystem.NcaUtils.Nca.OpenFileSystem(IStorage storage, NcaFsHeader header)
   at LibHac.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.FsSystem.NcaUtils.Nca.OpenFileSystem(NcaSectionType type, IntegrityCheckLevel integrityCheckLevel)`
snippet of codes is:
```dotnet
if (nca.Header.ContentType == NcaContentType.Program)
                        {
                            PartitionFileSystem codeFileSystem = (PartitionFileSystem)nca.OpenFileSystem(NcaSectionType.Code, IntegrityCheckLevel.IgnoreOnInvalid);
.
.
.
```
`PartitionFileSystem codeFileSystem = (PartitionFileSystem)nca.OpenFileSystem(NcaSectionType.Code, IntegrityCheckLevel.IgnoreOnInvalid);` throws the error.

Have you an idea how to get the the FileSystem from the nca?
PS: I tried with hactoolnet and I had same message

**Comment by Thealexbarney** [comment]
Are you sure you have the correct keys for the nca? Does extracting the nca with hactool work?

**Comment by kaktus40** [comment]
Well, I make a first loop to retrieve the rigthsId and the access key from .tik in the nsp and I inject the result in keyset.ExternalKeySet used to decrypt the nca `Nca nca = new Nca(keySet, new FileStorage(file))`.
This code works for all others nsp files

**Comment by Thealexbarney** [comment]
It sounds like the title key is incorrect. I'd try dumping the game again to see if that fixes it

**Comment by kaktus40** [comment]
Well, I extract manually the rightsId and the access key from the ticket embedded in the nsp file and try with the last version of hactoolnet to extract exefs but it failed again. Indeed, I have similar result when I alter the access key.
So the question is where do I find the real access key?

**Comment by slp32** [comment]
Both of the applications you mentioned use Sparse storage, and thus require you to handle them like you would a patch - using the `--basenca` option with the application program NCA, and the patch program NCA.

**Comment by kaktus40** [comment]
Hello, thanks for the hints. I'll work on it!

**Comment by Thealexbarney** [comment]
Using sparse storage shouldn't have anything to do with it. The problem you're describing sounds like you simply have an incorrect key. I'd try redumping the game from your Switch to make sure you have the correct ticket

**Comment by kaktus40** [comment]
Ok I redump the game!
