### ISSUE TITLE
ERROR: Offset must be a multiple of 16

### ISSUE THREAD

**Issue by i7ian** [Thealexbarney/LibHac#296]
hactoolnet -k prod.keys -t nca "C:\Users\7ian\Desktop\hac2l\secure\3b904a3fbceb1def9cf64369a5206543.nca" --romfsdir C:\Users\7ian\Desktop\hac2l\secure\romfs0

-----------------------------------------------
ERROR: Offset must be a multiple of 16

Additional information:
System.ArgumentException
   at LibHac.Tools.FsSystem.SectorStorage.ValidateSize(Int64 size, Int64 offset) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\SectorStorage.cs:line 93
   at LibHac.Tools.FsSystem.SectorStorage.Read(Int64 offset, Span`1 destination) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\SectorStorage.cs:line 32
   at LibHac.Tools.FsSystem.Aes128CtrStorage.Read(Int64 offset, Span`1 destination) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\Aes128CtrStorage.cs:line 64
   at LibHac.Tools.FsSystem.Aes128CtrExStorage.Read(Int64 offset, Span`1 destination) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\Aes128CtrExStorage.cs:line 86
   at LibHac.Tools.FsSystem.ConcatenationStorage.Read(Int64 offset, Span`1 destination) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\ConcatenationStorage.cs:line 50
   at LibHac.Fs.SubStorage.Read(Int64 offset, Span`1 destination) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Fs\SubStorage.cs:line 165
   at LibHac.FsSystem.StorageFile.DoRead(Int64& bytesRead, Int64 offset, Span`1 destination, ReadOption& option) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\FsSystem\StorageFile.cs:line 39
   at LibHac.Fs.Fsa.IFile.Read(Int64& bytesRead, Int64 offset, Span`1 destination, ReadOption& option) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Fs\Fsa\IFile.cs:line 56
   at LibHac.Fs.Fsa.IFile.Read(Int64& bytesRead, Int64 offset, Span`1 destination) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Fs\Fsa\IFile.cs:line 70
   at LibHac.Tools.FsSystem.FileReader.FillBuffer(Int64 offset, Int32 count, Boolean updatePosition) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\FileReader.cs:line 35
   at LibHac.Tools.FsSystem.FileReader.ReadInt64(Int64 offset, Boolean updatePosition) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\FileReader.cs:line 104
   at LibHac.Tools.FsSystem.FileReader.ReadInt64() in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\FileReader.cs:line 173
   at LibHac.Tools.FsSystem.RomFs.RomfsHeader..ctor(IFile file) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\RomFs\RomFsFileSystem.cs:line 321
   at LibHac.Tools.FsSystem.RomFs.RomFsFileSystem..ctor(IStorage storage) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\RomFs\RomFsFileSystem.cs:line 19
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(IStorage storage, NcaFsHeader header) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\NcaUtils\Nca.cs:line 500
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenFileSystem(Int32 index, IntegrityCheckLevel integrityCheckLevel) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\LibHac\Tools\FsSystem\NcaUtils\Nca.cs:line 480
   at hactoolnet.ProcessNca.<Process>g__OpenFileSystem|0_1(Int32 index, <>c__DisplayClass0_0&, <>c__DisplayClass0_1&) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\hactoolnet\ProcessNca.cs:line 261
   at hactoolnet.ProcessNca.<Process>g__OpenFileSystemByType|0_3(NcaSectionType type, <>c__DisplayClass0_0&, <>c__DisplayClass0_1&) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\hactoolnet\ProcessNca.cs:line 271
   at hactoolnet.ProcessNca.Process(Context ctx) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\hactoolnet\ProcessNca.cs:line 152
   at hactoolnet.Program.RunTask(Context ctx) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\hactoolnet\Program.cs:line 137
   at hactoolnet.Program.Run(String[] args) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\hactoolnet\Program.cs:line 110
   at hactoolnet.Program.Main(String[] args) in C:\Users\7ian\Desktop\hac2l\LibHac-master\LibHac-master\src\hactoolnet\Program.cs:line 20

**Comment by Thealexbarney** [comment]
It appears you're trying to open a patch nca without the base nca. You can't open the patch by itself. You need the base nca as well

**Comment by i7ian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by i7ian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
